# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- development
- production

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: 'echo $(Build.SourceBranchName)'
  displayName: 'echo SourceBranchName'

- script: 'echo "on Master branch "'
  displayName: '[Run]Master Branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))

- script: 'echo "on Development branch "'
  displayName: '[Run]Development Branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/development'))

- script: 'echo "on Production branch "'
  displayName: '[Run]Production Branch'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/production'))